### ISSUE TITLE
Warning when importing via webpack

### ISSUE THREAD

**Issue by luanpotter** [spencerwi/Comparators.js#3] opened 2019-02-19 17:55 UTC
I'm getting this warning for a while in my project:

```
client:148 ./node_modules/comparators/dist/comparators.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

I love your lib a lot, it helps me to write way prettier code. Is there any reason or fix for this message?

I'm importing via webpack, babel and npm :)

**Comment by spencerwi** [comment] 2019-04-26 19:14
Hi @luanpotter! Sorry it took me so long to get back to this -- for some reason, I don't get notified by Github about issues. I probably need to fix my notification settings somewhere.

I'll take a look when I get a chance to see if I can clean this up. 

Glad you like this lib, and thanks for using it!

**Comment by spencerwi** [comment] 2019-05-09 12:38
For an update here: I'm still looking into the best route here. That warning appears because this library is distributed as a "UMD" module (one that works "isometrically", of sorts, in "module-less" browser, AMD, and CommonJS environments without requiring separate versions of the file. The "wrapper" that is generated around a UMD module looks for the existence of a "require" function, and uses it if it exists, which is why webpack/babel are complaining.

As such, making that warning go away is a bit more involved of a fix, as it requires coming up with a different strategy for distributing this library. I'm still trying to figure out what the best approach is. Theoretically, ES6 modules are "the standard", but in practice, they don't work out-of-the-box with Node.js (unless you enable a command-line flag), so that option seems like a regression for nodejs users. I don't want to _require_ people (pun intended) to install multiple dependencies to use this smallish library, so I'd like to avoid a route where I just go with ES6 and tell users to set up babel.

In your setup, is there a way you can set up your build pipeline to recognize a UMD module? If so, I may add that to the documentation of this module so that others who see the same warning can resolve it.

**Comment by spencerwi** [comment] 2019-05-16 16:08
@luanpotter Version 3.0.1 is published now; in it, you'll find a purely-Commonjs format that should make Webpack happy, and a UMD format that can be used pretty much anywhere. I'm going to go ahead and close this issue, as the problem should be resolved now, but if you run into more problems, feel free to reopen it.

**Closed as completed by spencerwi** 2019-05-16 16:08 UTC

**Comment by luanpotter** [comment] 2019-05-16 16:54
Thanks, I'll update right away!
